apiVersion: admin.enmasse.io/v1beta1
kind: BrokeredInfraConfig
metadata:
  labels:
    app: enmasse
  name: scenario2infraconfig
  namespace: enmasse-infra
spec:
  admin:
    resources:
      memory: 512Mi
    podTemplate:
      metadata:
        labels:
          agent-type: prod
  broker:
    addressFullPolicy: FAIL
    resources:
      memory: 4Gi
      storage: 20Gi
    podTemplate:
      metadata:
        labels:
          broker-type: prod
